### ISSUE TITLE
Fix `extra_requires`

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#260]
In two different local environemnts, and the CI, the command `pip install -e .[opt]` results in `WARNING: mala 0.2.0 does not provide the extra 'opt'`. I am unsure why. The most recent setuptools version this was tested with is 59.5.0 (because the current torch version breaks with versions higher then that). 

Comment by @DanielKotik:
Once this is fixed we need to make the approbriate changes in
```yml
# cpu-tests.yml
- name: Install mala package
  # ...
  run: |
     # ...
     # install extra dependencies
     pip install oapackage  # change to → pip install -e .[opt]
     pip install pytest     # change to → pip install -e .[test]
```
This then would also serve as a test indirectly.
